const SpeakerImages = {
  'A.J.': require('./aj.jpg'),
  'Al Brown': require('./al-brown.jpg'),
  'Andy Bernard': require('./andy-bernard.jpg'),
  'Angela Martin': require('./angela-martin.jpg'),
  'Captain Jack': require('./captain-jack.jpg'),
  'Carol Stills': require('./carol-stills.jpg'),
  'Cathy Simms': require('./cathy-simms.jpg'),
  'Charles Miner': require('./charles-miner.jpg'),
  'Clark Green': require('./clark-green.jpg'),
  'Creed Bratton': require('./creed-bratton.jpg'),
  'Danny Cordray': require('./danny-cordray.jpg'),
  'Darryl Philbin': require('./darryl-philbin.jpg'),
  'David Wallace': require('./david-wallace.jpg'),
  'Deangelo Vickers': require('./deangelo-vickers.jpg'),
  'Donna Newton': require('./donna-newton.jpg'),
  'Dwight Schrute': require('./dwight-schrute.jpg'),
  'Erin Hannon': require('./erin-hannon.jpg'),
  'Gabe Lewis': require('./gabe-lewis.jpg'),
  'Hank Tate': require('./hank-tate.jpg'),
  'Helene Beesly': require('./helene-beesly.jpg'),
  'Holly Flax': require('./holly-flax.jpg'),
  'Jan Levinson': require('./jan-levinson.jpg'),
  'Jessica (Vance Refridgeration)': require('./jessica-vance-refrigeration.jpg'),
  'Jim Halpert': require('./jim-halpert.jpg'),
  'Jo Bennett': require('./jo-bennett.jpg'),
  'Josh Porter': require('./josh-porter.jpg'),
  'Karen Filippelli': require('./karen-filippelli.jpg'),
  'Katy Moore': require('./katy-moore.jpg'),
  'Kelly Kapoor': require('./kelly-kapoor.jpg'),
  'Kevin Malone': require('./kevin-malone.jpg'),
  'Meredith Palmer': require('./meredith-palmer.jpg'),
  'Michael Scarn': require('./michael-scarn.jpg'),
  'Michael Scott': require('./michael-scott.jpg'),
  'Mose Schrute': require('./mose-schrute.jpg'),
  'Nate Nickerson': require('./nate-nickerson.jpg'),
  'Nellie Bertram': require('./nellie-bertram.jpg'),
  'Oscar Martinez': require('./oscar-martinez.jpg'),
  'Pam Beesly': require('./pam-beesly.jpg'),
  'Pam Halpert': require('./pam-beesly.jpg'),
  'Pete Miller': require('./pete-miller.jpg'),
  'Phyllis Lapin': require('./phyllis-lapin.jpg'),
  'Phyllis Vance': require('./phyllis-lapin.jpg'),
  'Robert California': require('./robert-california.jpg'),
  'Roy Anderson': require('./roy-anderson.jpg'),
  'Ryan Howard': require('./ryan-howard.jpg'),
  'Stanley Hudson': require('./stanley-hudson.jpg'),
  'Susan California': require('./susan-california.jpg'),
  'Toby Flenderson': require('./toby-flenderson.jpg'),
  'Todd Packer': require('./todd-packer.jpg'),
  'Val Johnson': require('./val-johnson.jpg'),
  Brian: require('./brian.jpg'),
  Eric: require('./eric.jpg'),
  Jessica: require('./jessica.jpg'),
  Maurie: require('./maurie.jpg'),
  Megan: require('./megan.jpg'),
  Nick: require('./nick.jpg'),
  Trevor: require('./trevor.jpg'),
  Unknown: require('./no-image.jpg')
}

export default SpeakerImages
